BestRestaurant/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext
  {
    public DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }

    public BestRestaurantContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurant/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public List<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurant/Models/Restaurant.cs
namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Description { get; set; }
    public string Name { get; set; }
    public string Review { get; set; }
    public int CuisineId { get; set; }
    public Cuisine Cuisine { get; set; }
  }
}

BestRestaurant/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.Include(cuisine => cuisine.Restaurants).FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Cuisines.Update(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurant/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantsController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants
        .Include(restaurant => restaurant.Cuisine)
        .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      if (restaurant.CuisineId == 0)
      {
        return RedirectToAction("Create");
      }
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
        .Include(restaurant => restaurant.Cuisine)
        .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Restaurants.Update(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h4>Add a new cuisine type</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Description, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Description)

  <input type="submit" value="Add new cuisine" />
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurant/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Are you sure you want to delete this cuisine type?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Cuisine list", "Index")

BestRestaurant/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine
@using BestRestaurant.Models

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.Restaurants.Count == 0)
{
  <h3>No restaurants have been added to this cuisine type yet!</h3>
}
else
{
  <h3>Restaurants:</h3>
  <ul>
    @foreach (Restaurant restaurant in Model.Restaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Cuisine Type", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine Type", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Add Restaurant", "Create", "Restaurants")</p>
<p>@Html.ActionLink("Back to Cuisine List", "Index")</p>

BestRestaurant/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cuisine type: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Name, new {@class = "labelcolor"})
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Cuisine List", "Index")</p>

BestRestaurant/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
<div>
<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No cuisines have been added yet!</h3>
} 

<ul>
  @foreach(Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
  }
</ul>
</div>

<ul class="navbar">
<li class="navbar">@Html.ActionLink("Add Cuisine", "Create")</li>
<li class="navbar">@Html.ActionLink("Add Restaurant", "Create", "Restaurants")</li>
<li class="navbar">@Html.ActionLink("Home", "Index", "Home")</li>
<li class="navbar">@Html.ActionLink("Restaurants", "Index", "Restaurants")</li>
<li class="navbar">@Html.ActionLink("Cuisine", "Index", "Cuisines")</li>
</ul>

BestRestaurant/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div>
<h1>Welcome to Find a Restaurant!</h1>
</div>

<ul class="navbar">
<li class="navbar">@Html.ActionLink("Home", "Index", "Home")</li>
<li class="navbar">@Html.ActionLink("Restaurants", "Index", "Restaurants")</li> 
<li class="navbar">@Html.ActionLink("Cuisines", "Index", "Cuisines")</li>
</ul>

BestRestaurant/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h1>Add a new Restaurant</h1>

<p><strong>NOTE:</strong> You need to have at least one Cuisine before you can add a Restaurant!</p>
<p>Go to @Html.ActionLink("this page", "Create", "Cuisines") to create a Cuisine.</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.Review, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Review)

  @Html.LabelFor(model => model.Cuisine, new {@class = "labelcolor"})
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Add new Restaurant" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Restaurants", "Index")</p>

BestRestaurant/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h1>Are you sure you want to delete this?</h1>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

BestRestaurant/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h1>Restaurant Details</h1>

<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Cuisine): @Html.DisplayFor(model => model.Cuisine.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h1>Edit</h1>

<h4>Edit this item: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name, new {@class = "labelcolor"})
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Description, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.Review, new {@class = "labelcolor"})
  @Html.TextBoxFor(model => model.Review)

  @Html.LabelFor(model => model.Cuisine, new {@class = "labelcolor"})
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
<div>
  <h1>Restaurant</h1>

  @if (@Model.Count == 0)
  {
    <h3>No Restaurants have been added yet!</h3>
  }
  else
  {
  <ul>
    @foreach (Restaurant restaurant in Model)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Name</li>
    }
  </ul>
  }
</div>

<ul class="navbar">
  <li class="navbar">@Html.ActionLink("Add Restaurant", "Create")</li>
  <li class="navbar">@Html.ActionLink("Home", "Index", "Home")</li>
  <li class="navbar">@Html.ActionLink("Restaurants", "Index")</li>
  <li class="navbar">@Html.ActionLink("Cuisines", "Index", "Cuisines")</li>
</ul>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Restaurants List!</title>
    <link 
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>